const APP_BAR_TEXT="Discover";
const BEST_POPULAR_FILMS_AND_SERIALS_TEXT="BEST POPULAR FILMS AND SERIALS";
const SHOW_CASES_TEXT="SHOWCASES";
const MORE_SHOW_CASES_TEXT="MORE SHOWCASES";
const BEST_ACTORS="BEST ACTORS";
const MORE_ACTORS="MORE ACTORS";